package frc.robot.subsystems;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
<<<<<<< HEAD
=======

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.REVLibError;
>>>>>>> 7fc3df1399d0b14c1dfbecdb0c0c1acb98d9a692
import com.revrobotics.CANSparkMax.IdleMode;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;

<<<<<<< HEAD
=======
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
>>>>>>> 7fc3df1399d0b14c1dfbecdb0c0c1acb98d9a692
public class Acquisition extends SubsystemBase {

    private CANSparkMax aquisitionMotor;

    public Acquisition() {
<<<<<<< HEAD
        aquisitionMotor = new CANSparkMax(8, MotorType.kBrushless);
        aquisitionMotor.restoreFactoryDefaults();
        aquisitionMotor.setInverted(false);
        aquisitionMotor.setIdleMode(IdleMode.kCoast);
=======
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
aquisitionMotor = new CANSparkMax(8, MotorType.kBrushless);
 
 aquisitionMotor.restoreFactoryDefaults();  
aquisitionMotor.setInverted(false);
aquisitionMotor.setIdleMode(IdleMode.kCoast);
  


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
>>>>>>> 7fc3df1399d0b14c1dfbecdb0c0c1acb98d9a692
    }

    @Override
    public void periodic() {
    }

    @Override
    public void simulationPeriodic() {
    }
}