package frc.robot.subsystems;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
<<<<<<< HEAD
=======

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.REVLibError;
>>>>>>> 7fc3df1399d0b14c1dfbecdb0c0c1acb98d9a692
import com.revrobotics.CANSparkMax.IdleMode;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;

<<<<<<< HEAD
=======
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
>>>>>>> 7fc3df1399d0b14c1dfbecdb0c0c1acb98d9a692
public class Shooter extends SubsystemBase {
    private CANSparkMax shooterMotor;
    private CANSparkMax turretMotor;

    public Shooter() {
        shooterMotor = new CANSparkMax(11, MotorType.kBrushless);

        shooterMotor.restoreFactoryDefaults();
        shooterMotor.setInverted(false);
        shooterMotor.setIdleMode(IdleMode.kCoast);

        turretMotor = new CANSparkMax(12, MotorType.kBrushless);

<<<<<<< HEAD
        turretMotor.restoreFactoryDefaults();
        turretMotor.setInverted(false);
        turretMotor.setIdleMode(IdleMode.kCoast);
=======
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
>>>>>>> 7fc3df1399d0b14c1dfbecdb0c0c1acb98d9a692
    }

    @Override
    public void periodic() {
    }

    @Override
    public void simulationPeriodic() {
    }
}